/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface P5Card {
    'borderColor': string;
    'innerColor': string;
    'outerColor': string;
  }
  interface P5CardAttributes extends StencilHTMLAttributes {
    'borderColor'?: string;
    'innerColor'?: string;
    'outerColor'?: string;
  }

  interface P5SelectOption {
    'value': string;
  }
  interface P5SelectOptionAttributes extends StencilHTMLAttributes {
    'value'?: string;
  }

  interface P5Select {
    'placeholder': string;
    'value'?: any | null;
  }
  interface P5SelectAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
    'value'?: any | null;
  }

  interface P5Slider {
    'max': number;
    'min': number;
    'step': number;
  }
  interface P5SliderAttributes extends StencilHTMLAttributes {
    'max'?: number;
    'min'?: number;
    'onChange'?: (event: CustomEvent) => void;
    'step'?: number;
  }

  interface P5Toggle {}
  interface P5ToggleAttributes extends StencilHTMLAttributes {
    'onChange'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'P5Card': Components.P5Card;
    'P5SelectOption': Components.P5SelectOption;
    'P5Select': Components.P5Select;
    'P5Slider': Components.P5Slider;
    'P5Toggle': Components.P5Toggle;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'p5-card': Components.P5CardAttributes;
    'p5-select-option': Components.P5SelectOptionAttributes;
    'p5-select': Components.P5SelectAttributes;
    'p5-slider': Components.P5SliderAttributes;
    'p5-toggle': Components.P5ToggleAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLP5CardElement extends Components.P5Card, HTMLStencilElement {}
  var HTMLP5CardElement: {
    prototype: HTMLP5CardElement;
    new (): HTMLP5CardElement;
  };

  interface HTMLP5SelectOptionElement extends Components.P5SelectOption, HTMLStencilElement {}
  var HTMLP5SelectOptionElement: {
    prototype: HTMLP5SelectOptionElement;
    new (): HTMLP5SelectOptionElement;
  };

  interface HTMLP5SelectElement extends Components.P5Select, HTMLStencilElement {}
  var HTMLP5SelectElement: {
    prototype: HTMLP5SelectElement;
    new (): HTMLP5SelectElement;
  };

  interface HTMLP5SliderElement extends Components.P5Slider, HTMLStencilElement {}
  var HTMLP5SliderElement: {
    prototype: HTMLP5SliderElement;
    new (): HTMLP5SliderElement;
  };

  interface HTMLP5ToggleElement extends Components.P5Toggle, HTMLStencilElement {}
  var HTMLP5ToggleElement: {
    prototype: HTMLP5ToggleElement;
    new (): HTMLP5ToggleElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'p5-card': HTMLP5CardElement
    'p5-select-option': HTMLP5SelectOptionElement
    'p5-select': HTMLP5SelectElement
    'p5-slider': HTMLP5SliderElement
    'p5-toggle': HTMLP5ToggleElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'p5-card': HTMLP5CardElement;
    'p5-select-option': HTMLP5SelectOptionElement;
    'p5-select': HTMLP5SelectElement;
    'p5-slider': HTMLP5SliderElement;
    'p5-toggle': HTMLP5ToggleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
